IDIOMAS = {
    'es': {
        'menu_file': 'Archivo',
        'menu_import': 'Importar',
        'menu_import_db': 'Abrir base de datos',
        'menu_import_csv': 'Nueva base de datos',
        'menu_exit': 'Salir',
        'menu_queries': 'Gráficos',
        'queries':'Consulta',
        'queries_SQL':'Consulta SQL',
        'menu_generate_queries': 'Generar consultas',
        'menu_query_assistant': 'Asistente de gráficos',
        'menu_help': 'Ayuda',
        'menu_about': 'Acerca de',
        'menu_language': 'Idioma',
        'spanish': 'Español',
        'english': 'Inglés',
        'about_message': 'OpenDataLite - Herramienta para gestión de datos',
        'new_data_base': 'Nueva base de datos',
        'import':'Importar',
        'CSV':'Archivo CSV',
        'execute':'Ejecutar',
        'table_db':'Tabla en la base de datos',
        'charts':'Gráficos',
        'visualizing_charts':'Visualización de Gráficos',
        'sucess':'Éxito',
        'select_db_title': 'Seleccionar base de datos',
        'warning_no_db_selected': 'No se seleccionó ninguna base de datos.',
        'error_title': 'Error',
        'error_no_db': 'No hay una base de datos cargada',
        'query_empty': 'La consulta SQL está vacía',
        'query_success': 'Consulta ejecutada exitosamente.',
        'no_results': 'No se encontró resultado de la consulta',
        'loading_title': 'Cargando',
        'executing_query': 'Ejecutando consulta, por favor espere...',
        'sql_error': 'Error de SQL',
        'sql_query_error': 'Error en la consulta SQL',
        'export_success': 'Consulta exportada correctamente.',
        'no_valid_query': 'No hay consulta válida para exportar.',
        'no_export_data': 'No hay resultados para exportar.',
        'index': 'Índice',
        'select': 'Seleccionar',
        'sqlite_file': 'Archivos SQLite',
        'csv_file': 'Archivos CSV',
        'warning': 'Advertencia',
        'no_select': 'No hay archivos seleccionados',
        'bd_name': 'Nombre de la base de datos',
        'table_name': 'Nombre de la tabla',
        'csv_select': 'Seleccionar CSV',
        'send': 'Enviar',
        'no_select_csv': 'No se ha seleccionado ningún archivo CSV',
        'csv_uploaded_successfully': 'El CSV se ha cargado correctamente',
        'error': 'Error',
        'error_csv': 'Error al cargar el CSV',
        'data_added': 'Datos agregados a la base de datos.',
        'error_load_csv_db': 'Error al cargar CSV en la base de datos',
        'select_sqlite': 'Seleccionar base de datos SQLite',
        'all_files': 'Todos los archivos',
        'bd_loaded': 'Base de datos cargada correctamente',
        'error_load_db': 'Error al cargar la base de datos',
        'structure': 'Estructura:',
        'table': 'Tablas',
        'select_database': 'Seleccionar base de datos',
        'select_a_database': 'Seleccionar una base de datos:',
        'confirm': 'Confirmar',
        'selected_database': 'Base de datos seleccionada',
        'using_database': 'Usando la base de datos',
        'do_not_select_db': 'No hay ninguna base de datos seleccionada',
        'load_tables': 'Cargar tablas',
        'column_x': 'Columna X:',
        'column_y': 'Columna Y:',
        'chart_type': 'Tipo de gráfico:',
        'query_preview': 'Vista previa de la consulta',
        'generate_chart': 'Generar gráfico',
        'error_generate_chart': 'Error al generar gráfico:',
        'chart': 'Gráfico',
        'error_load_table': 'Error al cargar la tabla',
        'select_database_table': 'Selecciona una base de datos y una tabla.',
        'select_table_columns': 'Selecciona tabla y columnas.',
        'no_column_select':'No se pudieron cargar las columnas:',
        'configuration':'Configuración',
        'insufficient_data_graph':'Datos insuficientes para graficar.',
        'error_reading_table':'Error leyendo la tabla.',
        'load_column': 'Cargar columnas',
        'generate_graph_first': 'Debe generar el gráfico primero',
        'save_report':'Guardar reporte como...',
        'success_pdf': 'PDF exportado correctamente'
    },
    'en': {
        'menu_file': 'File',
        'menu_import': 'Import',
        'menu_import_db': 'Open database',
        'menu_import_csv': 'New database',
        'menu_exit': 'Exit',
        'menu_queries': 'Grafic',        
        'queries_SQL':'SQL queries',
        'queries':'Querie',
        'menu_generate_queries': 'Generate queries',
        'menu_query_assistant': 'Grafic wizard',
        'menu_help': 'Help',
        'menu_about': 'About',
        'menu_language': 'Language',
        'spanish': 'Spanish',
        'english': 'English',
        'about_message': 'OpenDataLite - Data management tool',
        'new_data_base':'New Date Base',
        'import':'Import',
        'CSV':'File CSV',
        'execute':'Execute',
        'table_db':'Tables in the database',
        'charts':'Charts',
        'visualizing_charts':'Visualizing Charts',
        'sucess':'Éxito',
        'select_db_title': 'Select Database',
        'warning_title': 'Warning',
        'warning_no_db_selected': 'No database was selected.',
        'error_title': 'Error',
        'error_no_db': 'There is no database currently loaded.',
        'query_empty': 'The SQL query is empty.',
        'query_success': 'Query executed successfully.',
        'no_results': 'No results found from the query.',
        'loading_title': 'Loading',
        'executing_query': 'Executing query, please wait...',
        'sql_error': 'SQL Error',
        'sql_query_error': 'An error occurred in the SQL query',
        'export_success': 'Query exported successfully.',
        'no_valid_query': 'There is no valid query to export.',
        'no_export_data': 'There are no results to export.',
        'index': 'Index',
        'select': 'Select',
        'sqlite_file': 'SQLite Files',
        'csv_file': 'CSV Files',
        'warning': 'Warning',
        'no_select': 'No selected',
        'bd_name': 'Database Name',
        'table_name': 'Table Name',
        'csv_select': 'Select CSV',
        'send': 'Send',
        'no_select_csv': 'No CSV file selected.',
        'csv_uploaded_successfully': 'CSV uploaded successfully.',
        'error': 'Error',
        'error_csv': 'Error uploading CSV',
        'success': 'Success',
        'data_added': 'Data added to the database of data.',
        'error_load_csv_db': 'Error loading CSV into database',
        'select_sqlite': 'Select SQLite database',
        'all_files': 'All files',
        'bd_loaded': 'Database loaded successfully.',
        'error_load_db': 'Error loading database',
        'structure': 'Structure:',
        'table': 'Tables',
        'select_database': 'Select database',
        'select_a_database': 'Select a database:',
        'confirm': 'Confirm',
        'selected_database': 'Selected database',
        'using_database': 'Using database',
        'do_not_select_db': 'No database selected',
        'load_tables': 'Load tables',
        'column_x': 'Column X:',
        'column_y': 'Column Y:',
        'chart_type': 'Chart type:',
        'query_preview': 'Query preview',
        'generate_chart': 'Generate chart',
        'error_generate_chart': 'Error generating chart:',
        'chart': 'Chart',
        'error_load_table': 'Error loading table',
        'select_database_table': 'Select a database and table.',
        'select_table_columns': 'Select a table and columns.',
        'no_column_select': 'Could not load columns:',
        'configuration': 'Configuration',
        'insufficient_data_graph': 'Insufficient data to graph.',
        'error_reading_table': 'Error reading table.',
        'load_column': 'Load columns',
        'generate_graph_first': 'You must generate the graph first',
        'save_report': 'Save report as...',
        'success_pdf': 'PDF exported successfully'
    }
} 

idioma_actual = "es"

def obtener_texto(clave):
    return IDIOMAS.get(idioma_actual, {}).get(clave, f"[{clave}]")

def cambiar_idioma(idioma):
    global idioma_actual
    if idioma in IDIOMAS:
        idioma_actual = idioma
    else:
        raise ValueError(f"Idioma '{idioma}' no soportado.")
